// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using Foundation;
using UIKit;

namespace TermProject
{
	public partial class EventDetailViewController : UITableViewController
	{
		public EventDetailViewController (IntPtr handle) : base (handle)
		{
		}

		Event currentEvent { get; set; }

		public RootViewController Delegate {get;set;}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			SaveButton.TouchUpInside += (sender, e) => {
                currentEvent.Name = Name.Text;
                currentEvent.Month = Code.Text;

				Delegate.SaveEvent(currentEvent);
			};
			DeleteButton.TouchUpInside += (sender, e) => {
				if (currentEvent == null) return;
				Delegate.DeleteEvent(currentEvent);
			};
		}
		
		// this will be called before the view is displayed 
		public void SetEvent (RootViewController d, Event Event) {
			Delegate = d;
			currentEvent = Event;
		}
		// when displaying, set-up the properties
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
            if (currentEvent == null) currentEvent = new Event();;
            Name.Text = currentEvent.Name;
            Code.Text = currentEvent.Month;
		}
	}
}
