// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using Foundation;
using UIKit;

namespace TermProject
{
    public partial class EventDetailViewController : UITableViewController
    {
        public EventDetailViewController(IntPtr handle) : base(handle)
        {
        }

        MonthModel pickerModel = new MonthModel();
        Event currentEvent { get; set; }
        public string month;

        public RootViewController Delegate { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            monthPicker.Model = pickerModel;

            SaveButton.TouchUpInside += (sender, e) => {
                currentEvent.Name = nameTextField.Text;
                currentEvent.Day = dayTextField.Text;
                currentEvent.Month = pickerModel.months[monthPicker.SelectedRowInComponent(0)];

                Delegate.SaveEvent(currentEvent);
            };
            DeleteButton.TouchUpInside += (sender, e) => {
                if (currentEvent == null) return;
                Delegate.DeleteEvent(currentEvent);
            };
        }

        // this will be called before the view is displayed 
        public void SetEvent(RootViewController d, Event Event)
        {
            Delegate = d;
            currentEvent = Event;

        }
        // when displaying, set-up the properties
        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            if (currentEvent == null) currentEvent = new Event(); 

            nameTextField.Text = currentEvent.Name;
            string curMonth;
            if (currentEvent.Month == null)
                curMonth = month;
            else
                curMonth = currentEvent.Month;
            monthPicker.Select(pickerModel.GetRowsByMonth(curMonth),0,true);
            //monthPicker.Select(pickerModel.GetRowsByMonth(month), 0, true);
            dayTextField.Text = currentEvent.Day;
        }
    }
}
